### ISSUE TITLE
Support for notranslate="1"

### ISSUE THREAD

**Issue by dingedi** [argosopentech/translate-html#2]
Is it complicated to set up a system so that the words are not translated?

**Comment by PJ-Finlay** [comment]
https://community.libretranslate.com/t/how-to-override-few-translation/22/6

**Comment by dingedi** [comment]
I don't know if this really solves the problem because for example to translate a web page some words must not be translated (example brand names or other) and they have the attribute translate="no"

I think it would be useful to have it integrated directly into the library

example: 
`<div>Hello, this <span translate="no">word</span> will not be translate</div>`

**Comment by dingedi** [comment]
I made a pull request for this :)

**Comment by PJ-Finlay** [comment]
https://www.w3.org/International/questions/qa-translate-flag

**Comment by PJ-Finlay** [comment]
https://github.com/argosopentech/translate-html/pull/3
